### PR TITLE
Add typo-in-layer-name rule

### LINKED ISSUE #93: Implement `typo-in-layer-name`
If there's a folder among the top-level folders called `widgents`, for example, this rule should warn that it was probably `widgets` that was intended

### PR DESCRIPTION
**Pull request by Espate**
Resolves #93 

I checked a few packages which have built-in spellcheck feature, but they don't fit the needs due to:
- require additional dictionary, e.g. in `.aff` or `.dic` formats ([nodehun](https://github.com/Wulf/nodehun), [nspell](https://github.com/wooorm/nspell), [typojs](https://github.com/cfinke/Typo.js))
- archived repo (maybe not crucial, but still) ([node-spellchecker](https://github.com/atom/node-spellchecker))
- have a huge size ([natural](https://github.com/NaturalNode/natural), ~7MB)

So, I decided to use lightweight & fast package called [fastest-levenshtein](https://github.com/ka-weihe/fastest-levenshtein) which implements [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) algorithm.

### CODE REVIEW

**Review by illright — CHANGES_REQUESTED** [review]
Thanks for a thorough research of potential dependencies and a quick and solid solution! As usual, I have a suggestion regarding the rationale, but this time I also think we should make the rule more sophisticated.

Right now, it doesn't set an upper boundary on the levenshtein distance. In practice, that means that if I have a folder called `templates` in the root, it will be treated as a typo from "pages" (distance: 5), even though it's clearly not a typo, and has nothing to do with pages. Moreover, we should consider a case when the layer that we think was meant is actually present. So if there is `src/pages` and `src/templates`, the linter saying that `src/templates` is meant to be `src/pages` is even more ridiculous, as there already is a `pages`. Another thing to consider here is if a name of a folder has several words like `license-files`.

Ideally, we would bring in an actual typo detector, like the `nspell` project you mentioned, along with `dictionary-en`, which would be 500KB, a bit too much. I think we can still get by without it, by doing a matrix of levenshtein distances (LDs) between all available folders and all available layers, then picking out exactly one pair that is closest by LD and removing it from the search, so that no other pair can be formed with either of these. And we should probably consider 3 as the largest LD for a typo, so if it's more than that, then it's probably not a typo, but instead a different intention.

**Comment by Espate** [comment]
> Right now, it doesn't set an upper boundary on the levenshtein distance. In practice, that means that if I have a folder called `templates` in the root, it will be treated as a typo from "pages" (distance: 5), even though it's clearly not a typo, and has nothing to do with pages. Moreover, we should consider a case when the layer that we think was meant is actually present. So if there is `src/pages` and `src/templates`, the linter saying that `src/templates` is meant to be `src/pages` is even more ridiculous, as there already is a `pages`. Another thing to consider here is if a name of a folder has several words like `license-files`.
 
Good point, I thought the methodology forbids any custom layers, so it's not needed to take into account `templates` or `license-files` as valid inputs.

> I think we can still get by without it, by doing a matrix of levenshtein distances (LDs) between all available folders and all available layers, then picking out exactly one pair that is closest by LD and removing it from the search, so that no other pair can be formed with either of these. And we should probably consider 3 as the largest LD for a typo, so if it's more than that, then it's probably not a typo, but instead a different intention.

Let's talk about this a bit. Am I right that your proposal is to build a matrix like this?

|           | app | page | shraed | wigdets | fiatures |
|-----------|-----|------|--------|---------|----------|
| app       |  0  |  3   |   5    |    7    |    7     |
| pages     |  4  |  1   |   5    |    4    |    5     |
| shared    |  5  |  4   |   2    |    6    |    5     |
| widgets   |  7  |  5   |   6    |    2    |    6     |
| features  |  7  |  6   |   7    |    7    |    1     |

Then fix & exclude `app` (0), `page` | `fiatures` (1), `shraed` (2), etc.

If so, I guess it might be overhead a bit due to it's uncommon to have such amount of typos (1 is ok, maybe 2, but more - doubtful). Besides, if we set upper bound of Levenshtein distance as 3, there will not be a situation where there is a typo in the name of one layer, but the rule suggests another layer, because Levenshtein distance will be more than 3 and the rule will not complain at all.

**Comment by illright** [comment]
> I thought the methodology forbids any custom layers

It does, but some frameworks like Nuxt insist on having some extra folders, so we need to prepare for that

> Let's talk about this a bit. Am I right that your proposal is to build a matrix like this?

Yes, exactly

> If so, I guess it might be overhead a bit due to it's uncommon to have such amount of typos (1 is ok, maybe 2, but more - doubtful). Besides, if we set upper bound of Levenshtein distance as 3, there will not be a situation where there is a typo in the name of one layer, but the rule suggests another layer, because Levenshtein distance will be more than 3 and the rule will not complain at all.

I didn't fully understand this bit, could you elaborate please? As for the overhead, I think it's manageable, because it's 6 × <number of folders>, it's okay both in terms of memory and in terms of computing the LD (the library does it pretty fast)

**Comment by illright** [comment]
Ah, wait, I understand it now. Well, either way, we have to be able to tell that "shentities" is more probably entities than it is shared. I can come up with a more practical example later, but I think it's necessary to do the matrix regardless of where we set the upper bound

**Comment by Espate** [comment]
> Ah, wait, I understand it now. Well, either way, we have to be able to tell that "shentities" is more probably entities than it is shared.

That sounds reasonable. Agreed, in that case matrix will provide better suggestions.

> I can come up with a more practical example later, but I think it's necessary to do the matrix regardless of where we set the upper bound

We will be able to add it in specs, so it would be really useful.

**Comment by illright** [comment]
I found all the words that might technically somehow be in a project with distances 1 or 2 from the layer names:
- shared: `shard, hard, sealed, saved, shapes, staged`
- entities: `entries, fixtures, futures, gestures`
- pages: `cases, images, packs, panels, paths, places, saves, pip, zip`
- app: `amp, apt`

**Review by illright — APPROVED** [review]
Great stuff!

**Pull request merged**
