### PR TITLE
Fix 404s in rule description links

### LINKED ISSUE #122: v0.5.0 Validation and Link Reference Bugs
Hey team! Thanks for the great work you do! 
I have a regular React + TypeScript project. I've just updated your package to and v0.5.0 followed the migration guide but it seems that now it mischecks quite a lot of rules. 
For instance: 
```
┌ src\widgets\order
✘ This slice has no references. Consider removing it.
│
└ fsd/insignificant-slice (​https://github.com/feature-sliced/steiger/tree/master/packages/steiger-plugin-fsd/src/fsd/insignificant-slice​)
```
While it actually has reference, and v0.4.0 didn't complain about it.

Besides it seems it mischecks forbidden-imports rule, for instance in v0.4.0 it detected an error: 
```
┌ src\pages\auth\ui\Auth.tsx
✘ Forbidden import from higher layer "app".
│
└ forbidden-imports (​https://github.com/feature-sliced/steiger/tree/master/packages/steiger-plugin-fsd/src/forbidden-imports​)
```
cause by `import { checkAuth } from "@/app/store/userState";` but it's not detected in v0.5.0

Another mischeck is this one, there's no such warning in in v0.5.0, but detected in previous version. :
```
┌ src\entities\order
✘ This slice has only one reference in slice "features\order\filter-order". Consider merging them.
│
└ insignificant-slice (​https://github.com/feature-sliced/steiger/tree/master/packages/steiger-plugin-fsd/src/insignificant-slice​)
```

Besides it seems that referencial links are broken or something, although the articles explaining the issues are great!
image

For now I'm going to return to the previous version, until it gets fixed. 
Anyway keep up the great work!
Let me know if you need any other data from me to fix the issue!

### PR DESCRIPTION
**Pull request by daniilsapa**
References #122

### CODE REVIEW

**Review by illright — APPROVED** [review]
Two organizational things: 
1. Could you remove the "Resolves" from the PR description? It doesn't fix all of the problems in that issue, so we don't want to close the issue by merging this 
2. If it's not a hassle, could you make an issue to move the URL descriptions to plugins? Otherwise I can also make it

**Comment by daniilsapa** [comment]
1. Yep, makes sense
2. Yes, I'll open an issue to move that logic to plugins

**Comment by daniilsapa** [comment]
But gimme a half an hour, maybe I'll come up with a fix for the other issue

**Comment by daniilsapa** [comment]
@illright 
I renamed the PR and got the "Resoves" back. Let's cover 2 issues with a single PR and release. The second issue is a bit tricky, so I need more time to investigate it. I'll proceed tomorrow.

**Comment by illright** [comment]
I'd prefer if we separated PRs because it will simplify review. We can still link them to the issue with the word "References" (won't close it)

**Pull request merged**
