### PR TITLE
Add the workflow to publish package previews

### PR DESCRIPTION
**Pull request by illright**
This is an attempt to add pkg.pr.new

### CODE REVIEW

**Review by daniilsapa — APPROVED** [review]
It looks good so far, but I think we need a real run to see if it runs as expected

**Comment by illright** [comment]
@daniilsapa could you approve it again please? it only runs when someone approves, and the last run failed (I think I fixed it now)

**Comment by daniilsapa** [comment]
I see some warnings called out by CodeQL. They suggested us adding permissions for the workflow to improve security and ensure it does not touch what it mustn't.

e.g.
```
name: Publish Approved Pull Requests to pkg.pr.new
permissions:
  contents: read
  pull-requests: write
```

**Review by daniilsapa — APPROVED** [review]
🤞

**Pull request merged**
